FROM ubuntu:22.04
RUN apt-get update && apt-get install --yes --no-install-recommends git make
LABEL description=ceci_est_une_description_pour_les_méta_data
RUN git config --global init.defaultBranch main